[feat-26] .sql 파서 구현
iml1111/SejongSQL pull request #27
Opened 2022-04-18 15:23 UTC by 837477

2019 노승민 교수님 출처인, .sql 파일 7개 (약 7500개 데이터) 를 대상으로 테스트 진행 완료. (현재는 전부 무사 통과 !)
추가적으로 다양한 .sql 파일을 받아와서 더 테스트 해볼 예정인데, 현재 env API 구현중이라 우선 임시적으로 PR날립니다.
(혹시 추가적인 피드백 있으면 부탁드립니다.)
- close #26 

### 파서 규칙
본 파서는 파일 내부에, 다음과 같은 사전 조건 체킹 구문들은 다 무시함.
```
DROP DATABASE IF EXISTS  madang;
DROP USER IF EXISTS  madang@localhost;
create user madang@localhost identified WITH mysql_native_password  by 'madang';
create database madang;
grant all privileges on madang.* to madang@localhost with grant option;
commit;
USE madang;
```

해당 파서는 다음과 같이, 오직 CREATE TABLE / CREATE INDEX / INSERT 구문만 판단.
```
// 옳바른 예시 예시
CREATE TABLE userTbl
( userID CHAR(8) NOT NULL PRIMARY KEY,
  userName VARCHAR(10) NOT NULL,
  birthYear INT NOT NULL,
  addr CHAR(2) NOT NULL,
  mobile1 CHAR(3),
  mobile2 CHAR(8),
  height SMALLINT,
  mDate DATE,
	INDEX 'birth_index' ('birthYear') // 테이블 생성시, 인덱스 적용 방식
);
CREATE TABLE buyTbl
(  num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
   userID CHAR(8) NOT NULL,
   prodName CHAR(6) NOT NULL,
   groupName CHAR(4),
   price INT  NOT NULL,
   amount SMALLINT  NOT NULL,
   FOREIGN KEY (userID) REFERENCES userTbl(userID)
);

CREATE INDEX 'price_index' ON buyTbl ('price') // 테이블 생성후, 인덱스 적용 방식

INSERT INTO userTbl VALUES('YJS', '유재석', 1972, '서울', '010', '11111111', 178, '2008-8-8');
INSERT INTO userTbl VALUES('KHD', '강호동', 1970, '경북', '011', '22222222', 182, '2007-7-7');
INSERT INTO userTbl VALUES('KKJ', '김국진', 1965, '서울', '019', '33333333', 171, '2009-9-9');
INSERT INTO userTbl VALUES('KYM', '김용만', 1967, '서울', '010', '44444444', 177, '2015-5-5');
... (계속)

INSERT INTO buyTbl VALUES(NULL, 'KHD', '운동화', NULL   , 30,   2);
INSERT INTO buyTbl VALUES(NULL, 'KHD', '노트북', '전자', 1000, 1);
INSERT INTO buyTbl VALUES(NULL, 'KYM', '모니터', '전자', 200,  1);
INSERT INTO buyTbl VALUES(NULL, 'PSH', '모니터', '전자', 200,  5);
... (계속)
```
같은 내용이지만, 조금 더 자세한 것은 노션 참고 부탁드립니다.
https://organized-dime-3a4.notion.site/Env-81d8ffd2cfb14014a4ca1401cb035e7a

### 결과
![image](https://user-images.githubusercontent.com/37999795/163830564-05dd4267-28d3-40db-8876-b2a1ab944092.png)

2022-04-19 08:41 UTC, akshxl09 approved these changes
LGBT

2022-04-19 11:03 UTC, iml1111 requested changes
전반적으로 내부에서 함수를 추가로 사용해서 추상화시키면 더 좋은 코드가 되지 않을까 합니다. 덧붙여 주석도 ㅎㅎ..

2022-04-19 11:03 UTC, iml1111 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +                        table_flag = True
```python
table_flag = token.value == 'TABLE'
```

2022-04-19 11:03 UTC, iml1111 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +                            return None
None은 쿼리 파싱이 실패한 경우인가요?
단순하게 None을 반환할게 아니라 범용성을 위해 실패여부 및 실패사유를 함께 반환할 수 있는 객체를 주는게 어떨까 싶습니다.

2022-04-19 11:03 UTC, iml1111 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +        parsed='\n'.join(result),
해당 쿼리들이 \n를 넣어주어야 하는 이유가 뭔가요?
혹시 파일 저장까지 염두한거라면, 객체의 책임을 넘어선 것 같습니다.
여기까지는 리스트로 반환을 하되, 이 컨트롤러 밖에서 join()을 하는 것이 맞는것 같아요.

2022-04-19 11:06 UTC, iml1111 commented
> LGBT

이건 뭔뜻이노 ㅋㅋ

2022-04-19 11:20 UTC, 837477 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +                        table_flag = True
호우 쮙 ㅋㅋ

2022-04-19 11:20 UTC, 837477 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +                            return None
저도 좀 고민하였는데, 최종 결과 반환도 `namedtuple` 사용하면 통일되게 다시 수정할 수 있을 것 같네요 ㅎㅎ 고맙습니다.

2022-04-19 11:20 UTC, 837477 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +        parsed='\n'.join(result),
이것도 또한 고민하였으나 ㅋㅋㅋ,,
제 테스트 코드 맨 밑쪽을 보면,
```
# 한번에 실행
with db.cursor() as cursor:
         cursor.execute(test.parsed)
```
이런걸 좀 원하지 않았을까 싶어서 조인을 한것도 주었습니다.
이 역시도 그져 해당 모듈에서는 처리해줄 필요가 없을까요?..

2022-04-19 11:29 UTC, iml1111 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +        parsed='\n'.join(result),
좀 오버해서 피드백하긴 하자면 객체가 어디까지 책임을 맡을지에 대한 이야기입니다. 

밖에서 이 객체를 사용할 개발자가 이걸 단일 문자열로 원할지, 쿼리 리스트로 원할지에 대해서 범용성을 주어야 할 것 같아요. 

- 만약 개발자가 리스트를 원한다면, 반대로 저 문자열을
```
queries.split('\n')
```
으로 나누려고 할테니까요. 

- 더 나아가서 \n이 아니라 \r\n, \t, \n\n 등의 갖가지 개행중에 \n을 선택한 합리적인 이유도 있어야할 것 같습니다. 
- 그게 아니라면 저걸 추가로 받을 수 있게 하는게 좋을까요?
- 아니면 리스트, 문자열 둘다 반환가능하도록 한다?

이렇게 오지랖이 시작되면 끝이 없거든요, 물론 그만큼 이 모듈은 완벽해지겠지만..

2022-04-19 12:03 UTC, 837477 commented on sejongsql/module/query_analyzer/mysql/query_parser.py
> +        parsed='\n'.join(result),
맞습니다!..
그래서 제가 밑에 query_list를 또 주긴했어요! 근데 어차피 결과적으로 '\n'.join(query_list) == parsed 이긴합니다...
저도 좀 어디까지 봐줘야할지 애매해서, 말씀대로 애초에 query_list만 주면 원하는 입맛대로 사용할 수 있으니 뭔가 조금 더 유연할 거 같긴 하네요 ㅋㅋ
<img width="414" alt="image" src="https://user-images.githubusercontent.com/37999795/163998524-6b413d2a-6619-4dc0-a880-5566e1a5cb7e.png">

그럼 해당 모듈은, 파일에 있는 쿼리들을 한번에 excute를 하는 방식 / 한줄 한줄씩 excute 하는 방식을 고려해서 딱 두개를 주는거로 가보겠습니당

좋은 피드백 감사합니당~ 

+@ 아 추가적으로 '\n'으로 한거는 그냥 print() 했을때 보기 편해서요.. 마치 .sql 파일열어서 보는 느낌이라 선택했던겁니당 ㅎ

2022-04-19 12:23 UTC, 837477 commented
> 전반적으로 내부에서 함수를 추가로 사용해서 추상화시키면 더 좋은 코드가 되지 않을까 합니다. 덧붙여 주석도 ㅎㅎ..

넹 :) 이부분은 추가적으로 더 수정해보겠습니다~

2022-04-19 12:26 UTC, iml1111 approved these changes

2022-04-22 15:34 UTC, backgroundjun approved these changes

2022-04-23 10:53 UTC, merged