[feat-7] 사용자 API 구현
iml1111/SejongSQL pull request #9
Opened 2022-04-02 13:35 UTC by akshxl09

close #7 
model은 erd가 계속 수정되면서 바뀔 예정

2022-04-02 13:37 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +        try:
try-except 구문으로 해도 될지, 아니면 if문으로 처리해야 하는지 궁급합니다.

2022-04-02 13:46 UTC, akshxl09 commented on sejongsql/app_main/models/model.py
> +from xml.etree.ElementTree import Comment
제가 model에 싹 다 넣어놨는데, 이거 테이블별로 .py로 구분할까요?
이거 다음에 class 기능 구현하려고 했는데 통합으로 하니까 conflict가 우려되네요...

2022-04-02 14:01 UTC, iml1111 requested changes
일단 model쪽 코드 다 찢기전에 피드백쪽 먼저 확인부탁쓰

2022-04-02 14:01 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> +        if pw_update:
로직이 잘 이해가 안되서 그런데 왜 둘다 optional이  True이고, pw를 변경할때도 있고 안할 때도 있는거 같은데 어떻게 로직이 동작하는거지??

2022-04-02 14:01 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
유저 삭제 API는 만들지 않는게 어떨까 싶은데?

2022-04-03 08:46 UTC, akshxl09 commented on sejongsql/app_main/models/model.py
> +    class_id = models.ForeignKey(Class, on_delete=models.SET_NULL, db_column='class_id', null=True)
삭제되어도 기록은 남아있어야된다고 생각해서 일단 SET_NULL로 했습니다.

2022-04-03 08:46 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +        if len(data['pw']) < 8:
넵

2022-04-03 08:46 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +        if pw_update:
잘못 짠거같아서 다시 수정중입니다

2022-04-04 05:24 UTC, 837477 reviewed
뭔가, 왤케 모든 API에서 검증쪽 if가 덕지덕지 있는 듯하는 느낌이 들지?..
어쩔땐 서비스 특성상 그런거 같기도 하고, ORM 때문에 flask 프로젝트때처럼 우리 입맛대로 모델이 구조화가 안되서 그런거 같기도하고 ㅋㅋㅋ 나중에 고민좀 해봐야겠네

2022-04-04 05:24 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
관리자가 유저를 삭제 하는 API가 아닌, 본인 회원 탈퇴 같은데 있어야하지 않나??

2022-04-04 05:24 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +
음 그냥 내 개인적인 코드 스타일이긴한데, 그냥 개행이 아무 규칙없이 난사되어 있는 듯한 느낌이라서ㅋㅋ (전체적으로 들쑥 날쑥 개행이 되어서 보기 좀 불편함?) 그래서 너도 뭔가 너만의 코드 규율을 정하면 좋을듯?

나는 뭔가 함수 내에서도 특정한 기능을 진행하려고 필요한 코드들이 묶음(?) 형태로 존재하잖아? 얘네들을 기준으로 개행을 하거든
예를들어 위에 같은 경우는 유저 존재 확인할때 `user = User.objects.filter(id=data['id']).first()` 불러오고, `if not user` 하듯이 == 이렇게 뭔가 같은 기능을 위한 코드들은 개행안하고 묶어두고, 다음 기능을 할 때 개행을 시키는 등.

그리고 함수 호출할때, 위쪽에 인자가 많은 것들도 일자로 쓴 것들이 몇개 있었는데 PEP 8 코드 스타일 한번 참고해보고 수정해보는 것도 좋을듯!

2022-04-04 05:24 UTC, 837477 commented on sejongsql/app_main/urls.py
> +urlpatterns += [
뭔가 분류별로 나누고 싶어서그런거 같은데, `urlpatterns' 리스트 안에서 주석으로 구분하거나 / 아님 나는 뭐 개인적으로 크게 상관은 없음!
(나도 분류하는 강박 좀 있는거 같그든 ㅋㅋㅋ)

2022-04-04 05:24 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +    def put(self, request, **path):
아 인정, 플라스크는 데코레이터 url바로 보이는데 쟝고 임마는 url이랑 구조적으로 찢겨있으니 헷갈리네 ㅋㅋㅋㅋ

2022-04-05 08:45 UTC, 837477 approved these changes
저는 PASS 요!

2022-04-05 08:54 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> -        if len(data['id']) > 20:
id, pw를 값을 검증하는 기존 로직은 어디에 있나요??

2022-04-05 08:54 UTC, iml1111 commented on sejongsql/app_main/models/model.py
>  from django.db import models
이 친구도 models/model 보다는 다른 아이덴티티를 가진 이름이 좋지 않을까 싶습니다.

2022-04-05 08:54 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
본인 회원 탈퇴가 기획에 있었음?? 수업 듣다가 탈퇴하는 경우도 그럼 다 구상이 되어 있는거야?

2022-04-05 08:58 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> -        if len(data['id']) > 20:
아 rule을 따로 feature 브랜치 파서 만들고나서 추가하려고 했습니다

2022-04-05 09:04 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
아마 세종대 도메인을 쓰면 개인정보 관련해서 회원탈퇴가 필요하다고 본거같았는데, 한번 제대로 알아보겠음
우선은 회원 탈퇴되면 -> 해당 회원이 작성한 쿼리나 뭐 이런 것들은 그대로 남아있지만 -> Cascade로 회원이 NULL로만 바뀌게끔 해놨지

2022-04-05 09:04 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> -        if len(data['id']) > 20:
develop 브랜치는 무조건 완성된 기능이 올라가야 한다는 전제가 있기 때문에 여기서 하시는게 맞는것 같습니다.

develop 브랜치는 main 브랜치와 거의 동일하게 취급해주세용.

2022-04-05 09:09 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
개인정보 처리에 의한 회원 탈퇴는 반드시 즉시 탈퇴를 의미하는 건 아니라서

2022-04-05 09:12 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
> 내가 중간고사 시험기간에 실수로 계정을 탈퇴한거야 이거 어케 복구 프로세스가 진행되지? 거기까지 기획이 되어 잇냐는 의미 ㅇㅇ

오호,, 이런거 까지는 생각 못했네.
그럼 탈퇴를 하면 7일 후에 탈퇴가 되게끔 프로세스를 잡아두고 -> 7일 내로 다시 재가입하면 그 상태 그대로 유지되게끔 한번 방향을 잡아볼게

2022-04-05 09:14 UTC, iml1111 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
맨처음 기간에 실수로 남의 학번으로 가입한걸 우려하는 거라면 탈퇴할 기간을 제한하는 것도 나쁘지 않아보임. 
3월 2주까지만 탈퇴 가능 이런식으로 라던가?

2022-04-05 09:15 UTC, 837477 commented on sejongsql/app_main/views/users.py
> +    def delete(self, request, **path):
가입후 2주내로 탈퇴가 가능하다. 라고 제한을 하자는거지?? 
이것도 나쁘지 않은 방법이라고 생각은 드네! 오케이 한번 고려해보겠음

2022-04-05 10:10 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> -        if len(data['id']) > 20:
넵 작성해서 다시 커밋할게용

2022-04-05 16:11 UTC, backgroundjun requested changes

2022-04-05 16:23 UTC, backgroundjun commented on sejongsql/app_main/views/users.py
> +            return BAD_REQUEST("pw is not correct.")
예상 가능한 취약점을 기재하지 않았네요. 

예상 가능한 취약점은 무작위 대입 공격 입니다.
해커 입장에서 불특정 다수의 계정 탈취를 시도한다는 가정입니다.

무작위로 입력한 아이디가 DB 에 존재하는지 확인할 수 있다면,
패스워드를 무작위로 대입하여 성공할 때 까지 무작위로 대입합니다.
그렇지만, 입력한 아이디가 DB 에 존재하는지 확인할 수 없다면,
DB 에 존재하는지 확인할 수 있는 상황에 대비하여 **시간적 소모**가 줄며, 이는 **더 많은 계정을 탈취**할 수 있음을 의미합니다. 또한, 우리가 **보안 측면에서 대응할 수 있는 시간**도 짧아집니다.

물론, 앱에서 조치하지 않고 다른 방법도 있긴 합니다.
같은 IP 주소에서 단 시간에 비정상적인 통신 발생 시 Nginx 단에서 시간 당 요청 제한을 걸 수 있습니다.

2022-04-06 13:57 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +        #비밀번호 길이 검증. 8자 이상
넵 현재 validator 작성중에 있습니다!

2022-04-06 14:03 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +            pw = make_password(data['pw']),
네 장고에서 기본으로 제공하는 함수인데 SHA256해시와 함께 PBKDF2 알고리즘을 사용해서 암호화를 해주더라구요. 
그래서 찾아보니 88길이로 반환해줘서 max_length=88로 설정해놨습니다!

2022-04-07 11:54 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +            return FORBIDDEN("pw is not correct.")
@backgroundjun  회원탈퇴 부분이라 어차피 패스워드만 받아서 pw is not correct로 했는데 문제 있을까요?
내 정보 수정 API 부분도 마찬가지로 패스워드 받도록 되어있어서 똑같이 해놨습니다.

2022-04-07 11:54 UTC, iml1111 approved these changes
LGTM

2022-04-07 12:24 UTC, akshxl09 commented on sejongsql/app_main/views/users.py
> +            return BAD_REQUEST("pw is not correct.")
수정했습니다!

2022-04-07 15:51 UTC, backgroundjun commented on sejongsql/app_main/views/users.py
> +            return FORBIDDEN("pw is not correct.")
사실, `@jwt_required` Annotation 이 붙은 API 는 문제 없습니다! 👏👏

2022-04-07 15:51 UTC, backgroundjun approved these changes

2022-04-08 05:26 UTC, merged