[feat-94] Select Query Firewall 모듈 추가
iml1111/SejongSQL pull request #95
Opened 2022-05-28 13:10 UTC by backgroundjun

* Select Query Firewall 모듈 추가

2022-05-28 13:12 UTC, backgroundjun commented
# select-query-firewall
`MySQL` 문법의 `Select Statement` 구문을 입력받아, 악의적인 구문인지 판단하기 위한 파이썬 라이브러리입니다.  

세종대학교 2022년도 1학기 창의학기제 프로젝트 [SejongSQL](https://github.com/iml1111/SejongSQL) 에서 사용하기 위하여 개발되었습니다.

# Announcement

Raw 한 Query 를 입력받는 SejongSQL 서비스 특성 상 Whitelist 기반의 필터링이 불가하였습니다. Blacklist 기반으로 구성되어 오탐이 발생할 가능성이 있음을 미리 알립니다. 라이브러리 사용 중 오탐으로 인한 발생된 모든 피해에 대한 책임을 지지 않습니다.

# Usage

```python
from select_query_firewall import is_safe_select_query

safe_query = 'SELECT * FROM 고객;'
malicious_query = 'SELECT * FROM INFORMATION_SCHEMA.TABLES;'

print(is_safe_select_query(safe_query))  # -> (True, [])
print(is_safe_select_query(malicious_query))  # -> (False, ['INFORMATION_SCHEMA'])
```

2022-05-28 13:37 UTC, iml1111 requested changes
### 해당 모듈의 디렉터리 위치 변경이 필요해보입니다
현재  `module.query_analyzer.select_query_firewall`  경로로 세팅된 걸,
`module.query_analyzer.<mysql>.select_query_firewall` 로 바꾸는 게 좋을 것 같습니다.
코드를 러프하게 읽어보았을 때, MySQL에 어느 정도 종속성이 가지는 것으로 판단되기 때문에, 추후에 저희가 다른 RDBMS를 지원한다는 것을 고려한 것입니다.

+ 또한 해당 모듈의 경우, 제가 사전에 구현한 SELECTQueryValidator에 합쳐지는 형태로 구현되야 할 것 같아 해당 PR이 승인되면 제가 한번 수정하도록 하겠습니다.

### Python Maximum Recursion Depth
traverse 모듈이 재귀적으로 동작하는 것으로 보이는데요, Python의 재귀 최대 깊이 제한을 고려하여 너무나 깊은 쿼리의 경우 블락시키는 것이 좋을 것 같습니다.
+ 추가적으로, 너무나 긴 문자열의 쿼리 대해서 블락하는 것도 나쁘지 않아보이네요. @akshxl09

2022-05-28 13:43 UTC, akshxl09 approved these changes
확인했습니다!

2022-05-29 03:02 UTC, 837477 approved these changes

2022-05-30 13:05 UTC, iml1111 approved these changes

2022-05-30 13:05 UTC, iml1111 commented
가시죠!

2022-05-30 13:13 UTC, merged